#!/bin/bash
if [ ! -f neo4j-community-3.5.12-unix.tar.gz ]; then
  wget http://dist.neo4j.org/neo4j-community-3.5.12-unix.tar.gz
fi
tar -xvf neo4j-community-3.5.12-unix.tar.gz

echo "dbms.connectors.default_listen_address=0.0.0.0" >> neo4j-community-3.5.12/conf/neo4j.conf

neo4j-community-3.5.12/bin/neo4j-admin set-initial-password neo4jISZ
mkdir figures